xcodeproj 'SwiftCompanions.xcodeproj'

# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift

use_frameworks!

target 'SwiftCompanions' do
	   pod 'SwiftHTTP'
	   pod 'JSONJoy-Swift'
end

target 'SwiftCompanionsTests' do

end

target 'SwiftCompanionsUITests' do

end

